services:
  web:
    build: .
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    profiles:
      - default

  seed:
    build: .
    command: /bin/sh -c "python /app/project/manage.py migrate && python /app/project/manage.py seed_data"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    profiles:
      - seed

  celery:
    build: .
    command: celery -A project worker -l info
    working_dir: /app/project
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  celery-beat:
    build: .
    command: celery -A project beat -l info
    working_dir: /app/project
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - celery
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
