services:
  - type: web
    name: django-marketplace
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: marketplace-django-mus1.onrender.com
      - key: DEBUG
        value: "False"
    preDeployCommand: |
      python manage.py migrate
    startCommand: |
      python manage.py runserver 0.0.0.0:8000
