services:
  - type: web
    name: django-marketplace
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    preDeployCommand: |
      cd project && python manage.py migrate
    startCommand: |
      cd project && python manage.py runserver 0.0.0.0:8000
