# Generated by Django 4.2.20 on 2025-04-17 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='app_orders__cart_id_a2563a_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='app_orders__order_i_864a9d_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Время последнего изменения статуса заказа', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('shipped', 'Отправлен'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Выдан'), ('returned', 'Возвращён'), ('unclaimed', 'Невостребован')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status_updated_at'], name='app_orders__status__f5b054_idx'),
        ),
        migrations.AddField(
            model_name='refund',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='Сотрудник, инициировавший возврат (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='app_orders.order'),
        ),
    ]
