# Generated by Django 4.2.20 on 2025-04-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_refund_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
