# Generated by Django 4.2.20 on 2025-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_alter_shop_logo_shopcreationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='shopcreationrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shopcreationrequest',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/logos/'),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug'], name='app_shops_s_slug_67df2d_idx'),
        ),
    ]
