# Generated by Django 4.2.20 on 2025-04-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_refund_and_more'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='app_users_u_user_id_97499d_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pickup_point',
            field=models.ForeignKey(blank=True, help_text='ПВЗ, к которому привязан сотрудник (только для роли pp_staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='app_orders.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец'), ('admin', 'Администратор'), ('pp_staff', 'Сотрудник ПВЗ')], default='buyer', max_length=20),
        ),
    ]
